### ISSUE TITLE
懒得(buhui)发PR 留到这里

### ISSUE THREAD

**Issue by passioncsu** [flftfqwxf/mockserver#24]
这个东西我觉得非常适合我用,感谢作者,只不过为了方便弄个docker部署,方便大家搭建
把下面两个文件放到更目录
docker-compose up -d 就可以
# docker-compose.yaml
```
version: '2'
services:
  woodyapi:
    build: .
    ports:
      - "8033:8033"
    volumes:
      - ./:/root/mock
    depends_on:
      - db
  db:
    image: mysql:5.5
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_DATABASE=mysql

```
# Dockerfile
```
FROM node
WORKDIR /root/mock
RUN npm install
CMD ["npm", "start"]
```
